name: flutter_scroll_restoration
description: A Flutter widget that automatically saves and restores scroll positions for any scrollable widget.
version: 0.0.1
repository: https://github.com/mj12358/flutter-scroll-restoration
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - flutter
  - widget

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  dart_lintz: 1.2.3
  flutter_test:
    sdk: flutter
